In [2]:
import numpy as np

# Ordinary Python Syntax VS NumPy


In [3]:
# This is an ordinary python syntax
a = [1, 2, 3, 4, 5, 6]
print(a)

[1, 2, 3, 4, 5, 6]


In [4]:
print(a[1])

2


In [5]:
print(a[1:4])

[2, 3, 4]


In [6]:
print(a[-1])

6


# Array Attributes

In [7]:
# Same can be done with numpy
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [8]:
print(type(a))

<class 'numpy.ndarray'>


In [9]:
print(a[1])

2


In [10]:
print(a[1:])

[2 3 4 5 6]


In [11]:
print(a[:-2])

[1 2 3 4]


In [12]:
a[2] = 10
print(a)

[ 1  2 10  4  5  6]


In [13]:
a_mul = np.array([[1,2,3],[4,5,6], [7, 8, 9]])

In [14]:
print(a_mul[0])

[1 2 3]


In [15]:
print(a_mul[0, 1])

2


In [16]:
print(a_mul[0][1])

2


In [17]:
print(a_mul.shape)

(3, 3)


A more complex numpy array

In [18]:
a_mul = np.array([[[1,2,3,1],[4,5,6,1], [7,8,9,1]], [[1,1,1,1],[1,1,1,1],[1,1,1,1]]])

Array Attributes

In [19]:
print(a_mul.shape)

(2, 3, 4)


In [20]:
print(a_mul.ndim)

3


In [21]:
print(a_mul.size)

24


In [22]:
print(a_mul.dtype)

int64


NumPy Data Types

In [23]:
# this is not possible
a = np.array([[1, 2, 3],
              [4, "Hello", 6],
              [7, 8, 9]])
print(a.dtype)

<U21


In [24]:
# this still works
print(a[0][0])

1


In [25]:
# but the data type changes to a string or <U1 which means that it isn't properly defined
print(type(a[0][0]))

print("\nor\n")

print(a[0][0].dtype)
# the point is that you can only stores values with the same data type in a numpy array

<class 'numpy.str_'>

or

<U1


In [26]:
# there is an exception tho
# the below code type casts the string number into a float
a = np.array([[1, 2, 3],
              [4, "5", 6],
              [7, 8, 9]], dtype=np.float32)
print(a.dtype)
print(a[0][0].dtype)

float32
float32


In [27]:
print(a[1][1])

5.0


In [28]:
# whenever you don't have a primitive data type that we can type cast into, everything becomes an object
d = {'1': 'A'}

a = np.array([[1, 2, 3],
              [4, d, 6],
              [7, 8, 9]])
print(a.dtype)

object


In [29]:
# but since it's an object, whatever you put in it afterwards it will still be an object
a = np.array([[1, 2, 3],
              [4, d, 6],
              [7, 8, "hello"]])
print(a.dtype)
print(type(a[1][1]))
print(type(a[1][2]))
print(type(a[2][2]))

object
<class 'dict'>
<class 'int'>
<class 'str'>


In [30]:
# you can also specify the data types for each numpy array to whatever you want it to be

a = np.array([[1, 2, 3],
              [4, "5", 6],
              [7, 8, 9]], dtype="<U99")
print(a.dtype)
# tho when you tryna access the value inside the array, it will become a string
print(type(a[0][0]))
print(type(a[1][1]))
print(type(a[2][2]))

<U99
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Filling Arrays

In [31]:
a = np.full((2, 3, 4), 9)
print(a)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


In [32]:
a = np.zeros((2, 3, 3))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [33]:
a = np.ones((2, 3, 3))
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [34]:
# the difference between zeros and empty here is that empty reserves space in the memory
a = np.empty((2, 3, 3))
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [35]:
# this will generate
x_values = np.arange(0, 100, 5)
print(x_values)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [36]:
# this will generate values that spreads evenly on a given range
x_values = np.linspace(0, 100, 5)
print(x_values)

[  0.  25.  50.  75. 100.]


# NaN and Inf
---
Null and Infinite number

In [37]:
print(np.nan)

nan


In [38]:
print(np.inf)

inf


In [39]:
print(np.isnan(np.nan))
print(np.isinf(np.inf))

True
True


In [40]:
print(np.isnan(np.sqrt(-1)))

True


<ipython-input-40-ea7a60a0f3dd>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(-1)))


In [41]:
print(np.isinf(np.array([10])/0))

[ True]


<ipython-input-41-cfd748efb07b>:1: RuntimeWarning: divide by zero encountered in divide
  print(np.isinf(np.array([10])/0))


In [42]:
print(np.sqrt(-1))

nan


<ipython-input-42-41a4088c2eb8>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


In [43]:
print(np.array([10])/0)

[inf]


<ipython-input-43-d8f00b03af36>:1: RuntimeWarning: divide by zero encountered in divide
  print(np.array([10])/0)


# Mathematical Operations

In [44]:
l1 = [ x for x in range(0, 7)]
l2 = [ x for x in range(7, 14)]

a1 = np.array(l1)
a2 = np.array(l2)

print(l1)
print(l2)
print(a1)
print(a2)

[0, 1, 2, 3, 4, 5, 6]
[7, 8, 9, 10, 11, 12, 13]
[0 1 2 3 4 5 6]
[ 7  8  9 10 11 12 13]


In [45]:
print(l1 * 5)

[0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6]


In [46]:
print(a1 * 5)

[ 0  5 10 15 20 25 30]


In [47]:
# you can't add python list with a constant
try:
  print(l1 + 5)
except Exception as e:
  print(e)

can only concatenate list (not "int") to list


In [48]:
print(l1 + l2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]


In [49]:
print(a1 + 5)

[ 5  6  7  8  9 10 11]


In [50]:
print(a2 + 5)

[12 13 14 15 16 17 18]


In [51]:
print(a1 + a2)

[ 7  9 11 13 15 17 19]


In [52]:
print(a1 / a2)

[0.         0.125      0.22222222 0.3        0.36363636 0.41666667
 0.46153846]


In [53]:
print(a1 / 0)

[nan inf inf inf inf inf inf]


<ipython-input-53-d054f63e1930>:1: RuntimeWarning: divide by zero encountered in divide
  print(a1 / 0)
<ipython-input-53-d054f63e1930>:1: RuntimeWarning: invalid value encountered in divide
  print(a1 / 0)


In [54]:
try:
  print(l1 - 1)
except Exception as e:
  print(e)

unsupported operand type(s) for -: 'list' and 'int'


In [55]:
try:
  print(l2 - l1)
except Exception as e:
  print(e)

unsupported operand type(s) for -: 'list' and 'list'


In [56]:
print(a1 - a2)

[-7 -7 -7 -7 -7 -7 -7]


In [57]:
a1 = np.array([1,2,3])
a2 = np.array([[1], [2]])

In [58]:
print(a1 + a2)

[[2 3 4]
 [3 4 5]]


In [59]:
a1.shape

(3,)

In [60]:
a2.shape

(2, 1)

In [61]:
a3 = np.array([[[1,2,3],[1,2,3],[1,2,3]], [[1,2,3],[1,2,3], [1,2,3]], [[1,2,3], [1,2,3], [1,2,3]]])
a3.shape

(3, 3, 3)

In [62]:
np.sqrt(4)

2.0

In [63]:
a = np.array([[2**x for x in range(1, 6)],[3**x for x in range(1, 6)]])
print(a)

[[  2   4   8  16  32]
 [  3   9  27  81 243]]


In [64]:
print(np.sin(a))

[[ 0.90929743 -0.7568025   0.98935825 -0.28790332  0.55142668]
 [ 0.14112001  0.41211849  0.95637593 -0.62988799 -0.89000935]]


In [65]:
print(np.cos(a))

[[-0.41614684 -0.65364362 -0.14550003 -0.95765948  0.83422336]
 [-0.9899925  -0.91113026 -0.29213881  0.77668598 -0.45594228]]


In [66]:
print(np.tan(a))

[[-2.18503986  1.15782128 -6.79971146  0.30063224  0.66100604]
 [-0.14254654 -0.45231566 -3.2737038  -0.81099442  1.95202199]]


In [67]:
print(np.arcsin(a))

[[nan nan nan nan nan]
 [nan nan nan nan nan]]


<ipython-input-67-e160afb20a74>:1: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(a))


In [68]:
print(np.arccos(a))

[[nan nan nan nan nan]
 [nan nan nan nan nan]]


<ipython-input-68-cabd94871aca>:1: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(a))


In [69]:
print(np.arctan(a))

[[1.10714872 1.32581766 1.44644133 1.50837752 1.53955649]
 [1.24904577 1.46013911 1.53377621 1.55845127 1.56668112]]


In [70]:
print(np.exp(a))

[[7.38905610e+000 5.45981500e+001 2.98095799e+003 8.88611052e+006
  7.89629602e+013]
 [2.00855369e+001 8.10308393e+003 5.32048241e+011 1.50609731e+035
  3.41632440e+105]]


In [71]:
print(np.log(a))

[[0.69314718 1.38629436 2.07944154 2.77258872 3.4657359 ]
 [1.09861229 2.19722458 3.29583687 4.39444915 5.49306144]]


In [72]:
print(np.log2(a))

[[1.        2.        3.        4.        5.       ]
 [1.5849625 3.169925  4.7548875 6.33985   7.9248125]]


In [73]:
print(np.log10(a))

[[0.30103    0.60205999 0.90308999 1.20411998 1.50514998]
 [0.47712125 0.95424251 1.43136376 1.90848502 2.38560627]]


# Array Methods
---
reshape

In [74]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(np.append(a, [11, 12, 13]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]


In [75]:
print(np.insert(a, 3, [11, 12, 13]))

[ 1  2  3 11 12 13  4  5  6  7  8  9 10]


In [76]:
np.delete(a, 1)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.delete(a, 1, 0))
# 0  at the end represents a row
# 1 at the end represents a column

[[1 2 3]
 [7 8 9]]


# Structuring Methods

In [78]:
a = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20]])

In [79]:
print(a.shape)
print(a.reshape((5,4)))

(4, 5)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [80]:
print(a.reshape(20,))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [81]:
print(a.reshape(2, 10))

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [82]:
print(a.reshape(2,2,5))

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [83]:
print(a.reshape(2,5,2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


In [84]:
print(a.reshape(20, 1))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]


In [85]:
print(a.reshape(5, 2, 2))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


In [86]:
print(a.reshape(10,2))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


# resize

In [87]:
# while reshape doesn't immediately or directly change the array
# resize does
a.resize(10, 2)
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [88]:
a.resize(5, 4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


# flatten & ravel

In [89]:
# this function transform any dimensional array into one dimensional array
print(a.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [90]:
# this does the same but it only shows the one dimensional array version of the array
# while flatten returns the copy of the array in one dimensional format
print(a.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [91]:
var1 = a.flatten()
var1[2] = 100
print(var1)

[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]


In [92]:
var2 = [x for x in a.flat]
print(var2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


# Transpose

In [93]:
print(a.transpose())

[[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]


In [94]:
print(a.T)

[[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]


In [95]:
print(a.swapaxes(0,1))

[[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]


# Merging Arrays

# Concatenating Arrays

In [96]:
a1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a2 = np.array([[11,12,13,14,15],[16,17,18,19,20]])

In [97]:
a = np.concatenate((a1, a2), axis=0)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [98]:
a = np.concatenate((a1, a2), axis=1)
print(a)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


# Stacking

In [99]:
a = np.stack((a1, a2), axis=0)
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [100]:
a = np.stack((a1, a2), axis=1)
print(a)

[[[ 1  2  3  4  5]
  [11 12 13 14 15]]

 [[ 6  7  8  9 10]
  [16 17 18 19 20]]]


In [101]:
a = np.vstack((a1, a2))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [102]:
a = np.hstack((a1, a2))
print(a)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


# Splitting Arrays

In [103]:
print(np.split(a, 2, axis=0))

[array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15]]), array([[ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])]


In [104]:
print(np.split(a, 2, axis=1))

[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])]


# Aggregate Functions

In [105]:
a.min()

1

In [108]:
a.max()

20

In [109]:
a.mean()

10.5

In [115]:
a.sum()

210

In [110]:
a.std()

5.766281297335398

In [114]:
np.median(a)

10.5

# Random

In [116]:
np.random.randint(100)

61

In [117]:
np.random.randint(100, size=(5, 5))

array([[86, 59, 61, 72, 37],
       [86, 35, 91, 79, 32],
       [ 8, 55, 31, 45,  1],
       [82, 24, 43, 42, 92],
       [94, 98, 67,  4, 38]])

In [119]:
np.random.randint(80, 100, size=(5, 5))

array([[92, 90, 80, 86, 86],
       [88, 89, 89, 81, 97],
       [99, 95, 88, 85, 87],
       [96, 84, 94, 84, 84],
       [92, 98, 83, 90, 85]])

In [120]:
np.random.binomial(10, p=0.5, size=(5, 5))

array([[3, 5, 5, 9, 5],
       [7, 3, 5, 4, 4],
       [5, 4, 3, 8, 6],
       [3, 2, 4, 3, 8],
       [7, 6, 5, 5, 5]])

In [123]:
np.random.normal(loc=165, scale=10, size=(5, 5))

array([[168.09006969, 155.67663546, 162.76770099, 171.86657563,
        173.39256459],
       [176.53277504, 151.7100075 , 151.97549925, 171.16311197,
        160.53939711],
       [164.8203894 , 171.11355591, 148.6069657 , 161.85522747,
        180.66335449],
       [174.39068907, 162.84632316, 150.50768816, 162.23025484,
        152.61820938],
       [179.82742437, 166.81895668, 170.3576593 , 165.53864543,
        158.6823427 ]])

In [126]:
randa = np.random.choice(np.random.randint(100, size=(10, )), size=(5, 5))
randa

array([[75, 75, 75, 29, 41],
       [97, 97, 48, 75, 48],
       [75, 97, 48,  9, 56],
       [50, 41, 97, 48, 48],
       [97, 75,  6, 97,  9]])

# Exporting and Importing

In [128]:
np.save("myarray.npy", randa)

In [129]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [130]:
a = np.load("myarray.npy")
a

array([[75, 75, 75, 29, 41],
       [97, 97, 48, 75, 48],
       [75, 97, 48,  9, 56],
       [50, 41, 97, 48, 48],
       [97, 75,  6, 97,  9]])

In [131]:
np.savetxt("myarray.csv", randa, delimiter=",")

In [132]:
b = np.loadtxt("myarray.csv", delimiter=",")
b

array([[75., 75., 75., 29., 41.],
       [97., 97., 48., 75., 48.],
       [75., 97., 48.,  9., 56.],
       [50., 41., 97., 48., 48.],
       [97., 75.,  6., 97.,  9.]])